In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/amar5693/screen-time-sleep-and-stress-analysis-dataset/Smartphone_Usage_Productivity_Dataset_50000.csv

In [2]:
import pandas as pd
import numpy as np
import os

for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

data = pd.read_csv('/kaggle/input/datasets/amar5693/screen-time-sleep-and-stress-analysis-dataset/Smartphone_Usage_Productivity_Dataset_50000.csv')

print(data.head())

/kaggle/input/datasets/amar5693/screen-time-sleep-and-stress-analysis-dataset/Smartphone_Usage_Productivity_Dataset_50000.csv
  User_ID  Age  Gender      Occupation Device_Type  Daily_Phone_Hours  \
0      U1   58    Male    Professional     Android                1.3
1      U2   25    Male    Professional     Android                1.2
2      U3   19    Male         Student         iOS                5.3
3      U4   35  Female  Business Owner         iOS                5.8
4      U5   33    Male      Freelancer     Android                7.9

   Social_Media_Hours  Work_Productivity_Score  Sleep_Hours  Stress_Level  \
0                 6.7                        6          8.8             4
1                 1.5                        5          6.4             1
2                 5.7                        5          9.0             4
3                 2.5                        2          5.7             3
4                 1.3                        4          5.7             3

   App_Usage_Count  Caffeine_Intake_Cups  Weekend_Screen_Time_Hours
0               42                     1                        8.7
1               51                     3                        5.1
2               14                     5                        6.3
3               36                     6                       12.8
4               37                     5                        9.9

In [3]:
data.shape

(50000, 13)

In [4]:
data.columns

Index(['User_ID', 'Age', 'Gender', 'Occupation', 'Device_Type',
       'Daily_Phone_Hours', 'Social_Media_Hours', 'Work_Productivity_Score',
       'Sleep_Hours', 'Stress_Level', 'App_Usage_Count',
       'Caffeine_Intake_Cups', 'Weekend_Screen_Time_Hours'],
      dtype='object')

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   User_ID                    50000 non-null  object
 1   Age                        50000 non-null  int64
 2   Gender                     50000 non-null  object
 3   Occupation                 50000 non-null  object
 4   Device_Type                50000 non-null  object
 5   Daily_Phone_Hours          50000 non-null  float64
 6   Social_Media_Hours         50000 non-null  float64
 7   Work_Productivity_Score    50000 non-null  int64
 8   Sleep_Hours                50000 non-null  float64
 9   Stress_Level               50000 non-null  int64
 10  App_Usage_Count            50000 non-null  int64
 11  Caffeine_Intake_Cups       50000 non-null  int64
 12  Weekend_Screen_Time_Hours  50000 non-null  float64
dtypes: float64(4), int64(5), object(4)
memory usage: 5.0+ MB

In [6]:
data.isnull().sum()

User_ID                      0
Age                          0
Gender                       0
Occupation                   0
Device_Type                  0
Daily_Phone_Hours            0
Social_Media_Hours           0
Work_Productivity_Score      0
Sleep_Hours                  0
Stress_Level                 0
App_Usage_Count              0
Caffeine_Intake_Cups         0
Weekend_Screen_Time_Hours    0
dtype: int64

In [7]:
data.describe()

,Age,Daily_Phone_Hours,Social_Media_Hours,Work_Productivity_Score,Sleep_Hours,Stress_Level,App_Usage_Count,Caffeine_Intake_Cups,Weekend_Screen_Time_Hours
count,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.00000,50000.000000,50000.000000
mean,39.034960,6.509116,4.267250,5.503760,6.497744,5.504500,32.43898,3.004580,8.006844
std,12.414877,3.170903,2.164743,2.874806,1.449551,2.871095,16.12151,1.996657,3.461300
min,18.000000,1.000000,0.500000,1.000000,4.000000,1.000000,5.00000,0.000000,2.000000
25%,28.000000,3.800000,2.400000,3.000000,5.200000,3.000000,18.00000,1.000000,5.000000
50%,39.000000,6.500000,4.300000,5.500000,6.500000,6.000000,32.00000,3.000000,8.000000
75%,50.000000,9.200000,6.100000,8.000000,7.800000,8.000000,46.00000,5.000000,11.000000
max,60.000000,12.000000,8.000000,10.000000,9.000000,10.000000,60.00000,6.000000,14.000000

In [8]:
data.corr(numeric_only=True)

,Age,Daily_Phone_Hours,Social_Media_Hours,Work_Productivity_Score,Sleep_Hours,Stress_Level,App_Usage_Count,Caffeine_Intake_Cups,Weekend_Screen_Time_Hours
Age,1.000000,0.006147,-0.005589,-0.003480,-0.000640,-0.001512,-0.009490,-0.005242,0.003127
Daily_Phone_Hours,0.006147,1.000000,0.000591,-0.002404,-0.003434,-0.002762,0.004670,0.006465,-0.003123
Social_Media_Hours,-0.005589,0.000591,1.000000,0.003625,-0.000871,-0.002721,0.001831,0.009161,-0.008570
Work_Productivity_Score,-0.003480,-0.002404,0.003625,1.000000,0.003243,0.009786,0.001125,0.001253,-0.005343
Sleep_Hours,-0.000640,-0.003434,-0.000871,0.003243,1.000000,0.004691,0.000999,0.004251,-0.006457
Stress_Level,-0.001512,-0.002762,-0.002721,0.009786,0.004691,1.000000,-0.001272,0.001718,0.002671
App_Usage_Count,-0.009490,0.004670,0.001831,0.001125,0.000999,-0.001272,1.000000,-0.000096,-0.000530
Caffeine_Intake_Cups,-0.005242,0.006465,0.009161,0.001253,0.004251,0.001718,-0.000096,1.000000,0.002682
Weekend_Screen_Time_Hours,0.003127,-0.003123,-0.008570,-0.005343,-0.006457,0.002671,-0.000530,0.002682,1.000000

In [9]:
data.groupby("Gender")["Daily_Phone_Hours"].agg(["sum","mean","count","min","max"])

             sum      mean  count  min   max
Gender
Female  108580.1  6.509989  16679  1.0  12.0
Male    108981.2  6.522696  16708  1.0  12.0
Other   107894.5  6.494583  16613  1.0  12.0

In [10]:
high_usage = data[data["Daily_Phone_Hours"] > 5]
print(high_usage.head())

  User_ID  Age  Gender      Occupation Device_Type  Daily_Phone_Hours  \
2      U3   19    Male         Student         iOS                5.3
3      U4   35  Female  Business Owner         iOS                5.8
4      U5   33    Male      Freelancer     Android                7.9
5      U6   32  Female         Student     Android               10.9
6      U7   26    Male         Student         iOS                5.6

   Social_Media_Hours  Work_Productivity_Score  Sleep_Hours  Stress_Level  \
2                 5.7                        5          9.0             4
3                 2.5                        2          5.7             3
4                 1.3                        4          5.7             3
5                 4.2                        9          6.3             7
6                 6.1                        8          6.7             3

   App_Usage_Count  Caffeine_Intake_Cups  Weekend_Screen_Time_Hours
2               14                     5                        6.3
3               36                     6                       12.8
4               37                     5                        9.9
5               34                     5                        3.6
6                5                     3                        2.9

In [11]:
group_gender = data.groupby("Gender")["Daily_Phone_Hours"].mean()
print(group_gender)

Gender
Female    6.509989
Male      6.522696
Other     6.494583
Name: Daily_Phone_Hours, dtype: float64

In [12]:
data["Stress_Level"].count()

np.int64(50000)

In [13]:
data["Daily_Phone_Hours"].max()

12.0

In [14]:
data["Daily_Phone_Hours"].sum()

np.float64(325455.79999999993)

In [15]:
data["Sleep_Hours"].mean()

np.float64(6.497743999999999)

In [16]:
data["Sleep_Hours"].min()

4.0

In [17]:
data.groupby("Gender")["Daily_Phone_Hours"].agg(["sum","mean","min","max","count"])

             sum      mean  min   max  count
Gender
Female  108580.1  6.509989  1.0  12.0  16679
Male    108981.2  6.522696  1.0  12.0  16708
Other   107894.5  6.494583  1.0  12.0  16613